import { VehicleProp } from "./Vehicle";

export const MOCK_DATA: VehicleProp[] = [
  { id: 1, brand: "Opel", model: "Corsa", plate: "AA111AA", status: "free" },
  { id: 2, brand: "Ford", model: "Focus", plate: "BB222BB", status: "busy" },
  { id: 3, brand: "Toyota", model: "Yaris", plate: "CC333CC", status: "free" },
  {
    id: 4,
    brand: "Honda",
    model: "Civic",
    plate: "DD444DD",
    status: "maintenance",
  },
  { id: 5, brand: "BMW", model: "Series 1", plate: "EE555EE", status: "free" },
  { id: 6, brand: "Audi", model: "A3", plate: "FF666FF", status: "busy" },
  {
    id: 7,
    brand: "Mercedes",
    model: "A-Class",
    plate: "GG777GG",
    status: "free",
  },
  {
    id: 8,
    brand: "Volkswagen",
    model: "Golf",
    plate: "HH888HH",
    status: "busy",
  },
  { id: 9, brand: "Fiat", model: "Punto", plate: "II999II", status: "free" },
  {
    id: 10,
    brand: "Peugeot",
    model: "208",
    plate: "JJ000JJ",
    status: "maintenance",
  },
  { id: 11, brand: "Renault", model: "Clio", plate: "KK111KK", status: "free" },
  { id: 12, brand: "Nissan", model: "Micra", plate: "LL222LL", status: "busy" },
  { id: 13, brand: "Hyundai", model: "i20", plate: "MM333MM", status: "free" },
  {
    id: 14,
    brand: "Kia",
    model: "Rio",
    plate: "NN444NN",
    status: "maintenance",
  },
  { id: 15, brand: "Mazda", model: "2", plate: "OO555OO", status: "free" },
  {
    id: 16,
    brand: "Chevrolet",
    model: "Spark",
    plate: "PP666PP",
    status: "busy",
  },
  { id: 17, brand: "Seat", model: "Ibiza", plate: "QQ777QQ", status: "free" },
  {
    id: 18,
    brand: "Citroen",
    model: "C3",
    plate: "RR888RR",
    status: "maintenance",
  },
  { id: 19, brand: "Skoda", model: "Fabia", plate: "SS999SS", status: "free" },
  { id: 20, brand: "Mini", model: "Cooper", plate: "TT000TT", status: "busy" },
  { id: 21, brand: "Tesla", model: "S", plate: "UU111UU", status: "free" },
];
